# -*- coding: utf-8 -*-
"""intent pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tdku9jtVUq1cbshyYXCSB5IwXfZAUTA
"""

!pip install groq

import requests
from groq import Groq

AETHEX_KEY = "your aethex key"
GROQ_KEY = "your groq key"
BASE_URL = "https://api.aethexai.com/api/v1"

groq_client = Groq(api_key=GROQ_KEY)

#  TRANSCRIBE AUDIO
with open("your_audio_here.wav", "rb") as f:
    transcribe_response = requests.post(
        f"{BASE_URL}/transcribe",
        headers={"X-API-Key": AETHEX_KEY},
        files={"file": f},
        data={"language": "english"}
    )

# status code and full JSON response
print(f"Transcription API Status Code: {transcribe_response.status_code}")
print(f"Transcription API Raw Response: {transcribe_response.text}")

transcribe_response.raise_for_status() # Raise an exception for HTTP errors

transcript_text = transcribe_response.json()["text"]
print("Transcript:", transcript_text)

# PARSE INTENT
llm_response = groq_client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "system",
            "content": """You are a financial intent parser for Nigerian merchants.
Given a voice transcript, return ONLY valid JSON matching one of these:

{"intent": "CREATE_INVOICE", "client": "name", "amount": 150000, "memo": "reason"}
{"intent": "CHECK_BALANCE", "account_type": "high_yield_sub_account"}
{"intent": "RUN_NEGOTIATION", "counterparty": "name", "requested_amount": 50000}

Rules:
- amount must be a number. ₦150,000 = 150000, "fifty thousand" = 50000
- Return ONLY the JSON. No explanation, no extra text."""
        },
        {
            "role": "user",
            "content": transcript_text
        }
    ]
)

import json
parsed_intent = json.loads(llm_response.choices[0].message.content)
print("Parsed Intent:", parsed_intent)